(princ "Hello, welcome to the cafe!")
(format t "What is your name?~C> " #\Newline)
(defvar name (read-line))

(let ((menu '("Black coffee" "Espresso" "Latte" "Cappucino" "Tea"))
      (price 5)
      (quantity)
      (order))
(cond ((string= name "Ben")
    (print "You're not welcome here benny boy"))
      (t
       (format t "hello ~A, thank you so much for coming in today." name)
       (print menu)
       (format t "~A, what would you like to order? > " name)
       (setq order (read-line))
       (print "How many coffees would you like? > ")
       (setq quantity (read))
       (format t "Thank you, your total is: $~A" (* price quantity))
       (format t "Sounds good ~A, we'll have your ~A ~A ready soon!" name quantity order))))
